// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Felipe Augusto De Faria Freitas",
            "email": "felipeaug92@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cancelamento": {
            "post": {
                "description": "Realiza o cancelamento de boletos.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CreditoPessoal"
                ],
                "summary": "Cancelar Boleto.",
                "parameters": [
                    {
                        "description": "Dados da cobrança.",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CancelarCobrancaFrontendInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/config/db/set": {
            "post": {
                "description": "Reconfigura os valores do DB.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config"
                ],
                "summary": "Reconfigurar DB.",
                "parameters": [
                    {
                        "description": "Parâmetros do banco de dados.",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/config.APIDBPoolConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/config/env": {
            "post": {
                "description": "Configura variáveis de ambiente.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config"
                ],
                "summary": "Configurar variáveis de ambiente globais.",
                "parameters": [
                    {
                        "description": "Variáveis que se deseja alterar.",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/config.EnvVars"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/consulta": {
            "post": {
                "description": "Realiza a consulta de cobranças geradas para uma proposta específica.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CreditoPessoal"
                ],
                "summary": "Consultar Cobranças.",
                "parameters": [
                    {
                        "description": "Identificador da proposta.",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ConsultaCobrancaFrontEndInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ConsultaCobrancaResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/geracao": {
            "post": {
                "description": "Realiza a geracao de cobranças na API do BMP.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CreditoPessoal"
                ],
                "summary": "GerarCobranca Proposta.",
                "parameters": [
                    {
                        "description": "Dados da cobrança.",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.GerarCobrancaFrontendInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "config.APIDBPoolConfig": {
            "type": "object",
            "properties": {
                "connMaxIdleTime": {
                    "type": "integer"
                },
                "connMaxLifetime": {
                    "type": "integer"
                },
                "default": {
                    "type": "boolean"
                },
                "maxIdleConns": {
                    "type": "integer"
                },
                "maxOpenConns": {
                    "type": "integer"
                },
                "reconnect": {
                    "type": "boolean"
                }
            }
        },
        "config.EnvVars": {
            "type": "object"
        },
        "models.APIError": {
            "type": "object",
            "properties": {
                "hasError": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.APIMessage"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "result": {}
            }
        },
        "models.APIMessage": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "context": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "field": {
                    "type": "string"
                },
                "messageType": {
                    "type": "integer"
                }
            }
        },
        "models.APIResponse": {
            "type": "object",
            "properties": {
                "codigo": {
                    "type": "string"
                },
                "hasError": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Message"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "models.CancelarCobrancaFrontendInput": {
            "type": "object",
            "required": [
                "id_proposta",
                "id_proposta_parcela",
                "numero_acompanhamento",
                "numero_ccb",
                "url_webhook"
            ],
            "properties": {
                "codigoLiquidacao": {
                    "type": "string"
                },
                "id_convenio": {
                    "type": "integer"
                },
                "id_proposta": {
                    "type": "integer"
                },
                "id_proposta_parcela": {
                    "type": "integer"
                },
                "id_securitizadora": {
                    "type": "integer"
                },
                "numero_acompanhamento": {
                    "type": "string"
                },
                "numero_ccb": {
                    "type": "integer"
                },
                "url_webhook": {
                    "type": "string"
                }
            }
        },
        "models.ConsultaBoleto": {
            "type": "object",
            "properties": {
                "descricaoBoletoRegistro": {
                    "type": "string"
                },
                "dtCredito": {
                    "type": "string"
                },
                "dtExpiracao": {
                    "type": "string"
                },
                "linhaDigitavel": {
                    "type": "string"
                },
                "liquidacao": {
                    "type": "boolean"
                },
                "numeroBoleto": {
                    "type": "integer"
                },
                "operacaoBoletoRegistro": {
                    "type": "integer"
                },
                "qrCode": {
                    "$ref": "#/definitions/models.ConsultaBoletoQrCode"
                },
                "situacaoBoletoRegistro": {
                    "type": "integer"
                },
                "urlImpressao": {
                    "type": "string"
                }
            }
        },
        "models.ConsultaBoletoQrCode": {
            "type": "object",
            "properties": {
                "emv": {
                    "type": "string"
                },
                "imagem": {
                    "type": "string"
                }
            }
        },
        "models.ConsultaCobrancaFrontEndInput": {
            "type": "object",
            "required": [
                "id_convenio",
                "id_proposta",
                "id_securitizadora",
                "numero_acompanhamento"
            ],
            "properties": {
                "id_convenio": {
                    "type": "integer"
                },
                "id_proposta": {
                    "type": "integer"
                },
                "id_securitizadora": {
                    "type": "integer"
                },
                "numero_acompanhamento": {
                    "type": "string"
                },
                "numero_parcela": {
                    "type": "integer"
                }
            }
        },
        "models.ConsultaCobrancaLancamento": {
            "type": "object",
            "properties": {
                "descLancamento": {
                    "type": "string"
                },
                "dtLancamento": {
                    "type": "string"
                },
                "dtVencimento": {
                    "type": "string"
                },
                "informarFundo": {
                    "type": "boolean"
                },
                "viaBoleto": {
                    "type": "boolean"
                },
                "vlrAbatimento": {
                    "type": "integer"
                },
                "vlrDesconto": {
                    "type": "integer"
                },
                "vlrIOF": {
                    "type": "integer"
                },
                "vlrJuros": {
                    "type": "integer"
                },
                "vlrMora": {
                    "type": "integer"
                },
                "vlrMulta": {
                    "type": "integer"
                },
                "vlrPagamento": {
                    "type": "integer"
                },
                "vlrParcela": {
                    "type": "integer"
                },
                "vlrParcelaAtualizado": {
                    "type": "integer"
                },
                "vlrSaldoParcela": {
                    "type": "integer"
                },
                "vlrTarifas": {
                    "type": "integer"
                }
            }
        },
        "models.ConsultaCobrancaMessage": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "context": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "field": {
                    "type": "string"
                },
                "messageType": {
                    "type": "integer"
                }
            }
        },
        "models.ConsultaCobrancaParcela": {
            "type": "object",
            "properties": {
                "boletos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ConsultaBoleto"
                    }
                },
                "codigoParcela": {
                    "type": "string"
                },
                "dtVencimento": {
                    "type": "string"
                },
                "dtVencimentoAtual": {
                    "type": "string"
                },
                "lancamentos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ConsultaCobrancaLancamento"
                    }
                },
                "nroOrdemPagamento": {
                    "type": "string"
                },
                "nroParcela": {
                    "type": "integer"
                },
                "pix": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ConsultaPix"
                    }
                },
                "situacao": {
                    "type": "integer"
                },
                "vlrDesconto": {
                    "type": "number"
                },
                "vlrParcela": {
                    "type": "number"
                },
                "vlrSaldoAtual": {
                    "type": "number"
                },
                "vlrTotalPago": {
                    "type": "number"
                }
            }
        },
        "models.ConsultaCobrancaResponse": {
            "type": "object",
            "properties": {
                "descricaoSituacaoAgenda": {
                    "type": "string"
                },
                "descricaoTipoContrato": {
                    "type": "string"
                },
                "documentoFederalCliente": {
                    "type": "string"
                },
                "dtCancelamento": {
                    "type": "string"
                },
                "dtInclusao": {
                    "type": "string"
                },
                "dtLiquidacao": {
                    "type": "string"
                },
                "ecCliente": {
                    "type": "string"
                },
                "hasError": {
                    "type": "boolean"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ConsultaCobrancaMessage"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "nomeCliente": {
                    "type": "string"
                },
                "nomeEmpresa": {
                    "type": "string"
                },
                "numeroProposta": {
                    "type": "integer"
                },
                "parcelas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ConsultaCobrancaParcela"
                    }
                },
                "qtdeParcelas": {
                    "type": "integer"
                },
                "result": {},
                "situacaoAgenda": {
                    "type": "integer"
                },
                "situacaoProposta": {
                    "type": "integer"
                },
                "vlrFinanciado": {
                    "type": "number"
                },
                "vlrRetencaoDiarioAprox": {
                    "type": "number"
                },
                "vlrTotalPago": {
                    "type": "number"
                }
            }
        },
        "models.ConsultaPix": {
            "type": "object",
            "properties": {
                "dtCredito": {
                    "type": "string"
                },
                "dtExpiracao": {
                    "type": "string"
                },
                "dtVencimento": {
                    "type": "string"
                },
                "emv": {
                    "type": "string"
                },
                "imagem": {
                    "type": "string"
                },
                "liquidacao": {
                    "type": "boolean"
                }
            }
        },
        "models.GerarCobrancaFrontendInput": {
            "type": "object",
            "required": [
                "data_expiracao",
                "data_vencimento",
                "id_forma_cobranca",
                "id_proposta",
                "id_proposta_parcela",
                "numero_acompanhamento",
                "numero_ccb",
                "numero_parcela",
                "token",
                "url_webhook"
            ],
            "properties": {
                "data_expiracao": {
                    "type": "string"
                },
                "data_vencimento": {
                    "type": "string"
                },
                "id_convenio": {
                    "type": "integer"
                },
                "id_forma_cobranca": {
                    "type": "integer"
                },
                "id_proposta": {
                    "type": "integer"
                },
                "id_proposta_parcela": {
                    "type": "integer"
                },
                "id_securitizadora": {
                    "type": "integer"
                },
                "numero_acompanhamento": {
                    "type": "string"
                },
                "numero_ccb": {
                    "type": "integer"
                },
                "numero_parcela": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                },
                "url_webhook": {
                    "type": "string"
                },
                "valor_parcela": {
                    "type": "number"
                }
            }
        },
        "models.Message": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "context": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "field": {
                    "type": "string"
                },
                "messageType": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "bmp-fgts.Confiapay.com.br",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "BMP Cobrança",
	Description:      "Microserviço de acesso aos serviços de geração de cobranças do BMP. \\n Para mais informações referentes aos dados a serem enviados, consulte a aba \"model\" na seção de body dos endpoints.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
